# =========================
# DRCT KD train (FINAL)
# =========================

# general settings
name: train_DRCT_KD_SRx2_df2k
model_type: DRCTKDModel
scale: 2
num_gpu: auto
manual_seed: 0

# -------------------------
# datasets
# -------------------------
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: datasets/DF2K/DF2K_train_HR_sub
    dataroot_lq: datasets/DF2K/DF2K_train_LR_bicubic/X2_sub
    meta_info_file: drct/data/meta_info/meta_info_DF2Ksub_GT.txt
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true

    # dataloader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: ./datasets/Set5/HR
    dataroot_lq: ./datasets/Set5/LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: ./datasets/Set14/HR
    dataroot_lq: ./datasets/Set14/LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk

# -------------------------
# student network (smaller)
# -------------------------
network_g:
  type: KDDRCT
  upscale: 2
  in_chans: 3
  img_size: 64
  window_size: 8
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.0
  depths: [6, 6, 6, 6]
  embed_dim: 96
  num_heads: [6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# -------------------------
# teacher network (bigger)
# -------------------------
network_t:
  type: KDDRCT
  upscale: 2
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.0
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# -------------------------
# paths (IMPORTANT)
# - student: no pretrain (scratch) OR you can put student ckpt here later
# - teacher: 반드시 pretrain_network_t 로 로드
# -------------------------
path:
  # student
  pretrain_network_g: ~
  strict_load_g: false

  # teacher
  pretrain_network_t: /home/vclab2080ti/Downloads/projects/DRCT/experiments/train_DRCT_SRx2_from_scratch_basic_50만번한거다.건들지마/models/net_g_latest.pth
  param_key_t: 'params_ema'
  strict_load_t: true

  # resume
  resume_state: ~

# -------------------------
# training
# -------------------------
train:
  ema_decay: 0.999

  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1

  # SR pixel loss
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  # KD loss weights
  kd_opt:
    w_out: 0
    w_feat: 0

# -------------------------
# validation
# -------------------------
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: false
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher

# -------------------------
# logger
# -------------------------
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
